In [70]:
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
import ssl
import pandas as pd
from collections import OrderedDict
from pandas import ExcelWriter
from pandas import ExcelFile

In [71]:
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

In [72]:
# Get stats for MS Dhoni

In [73]:
url="http://stats.espncricinfo.com/ci/engine/player/34102.html?class=1;template=results;type=batting;view=match"
html = urllib.request.urlopen(url, context=ctx).read()
player_name = ''

In [74]:
def get_table_headers():
    global player_name
    bs=BeautifulSoup(html, "lxml")
    mydivs = bs.findAll("div", {"class": "icc-home"})
    player_name = mydivs[0].findAll("a")[0].text.split("/")[2]
    temp_data=OrderedDict()
    list_of_dict=[]
    bs=BeautifulSoup(html, "lxml")
    headers_soup=bs.find_all("tr",{"class":"headlinks"})
    headers_tag = headers_soup[0].find_all("th")
    list_of_headers = []
    for header in headers_tag:
        list_of_headers.append(header.text)
    return list_of_headers

In [75]:
def get_stats_list():
    temp_data=OrderedDict()
    list_of_dict=[]
    bs=BeautifulSoup(html, "lxml")
    table_body=bs.find_all('tbody')
    stats_table = table_body[1]
    rows = stats_table.find_all("tr")
    table_data_list = []
    for row in rows:
        row_data = []
        col = row.find_all("td")
        row_data = [c.text.strip() for c in col]
        table_data_list.append(row_data)
    return table_data_list

In [76]:
list_of_headers = get_table_headers()
list_of_headers[-1] = 'Match No'

table_data_list = get_stats_list()

In [77]:
data_frame = pd.DataFrame(table_data_list)
data_frame.columns = list_of_headers

In [78]:
def formatRuns(runs):
    runs = runs.replace("*",'')
    try:
        return int(runs)
    except:
        return 0

In [79]:
def formatDate(date):
    year = date.split(" ")[-1]
    return year

In [80]:
def clean_data_frame(data_frame):
    data_frame['Bat1'] = data_frame['Bat1'].apply(lambda runs: formatRuns(runs))
    data_frame['Bat2'] = data_frame['Bat2'].apply(lambda runs: formatRuns(runs))
    data_frame['Runs'] = data_frame['Runs'].apply(lambda runs: formatRuns(runs))
    data_frame['Year'] = data_frame['Start Date'].apply(lambda date: formatDate(date))
    return data_frame

In [81]:
data_frame = clean_data_frame(data_frame)

In [82]:
res = data_frame.groupby(['Year']).agg({'Bat1': 'sum','Bat2':'sum', 'Opposition':'count'})
res=res.rename(columns = {'Opposition':'Matches'})
dictio = res.to_dict('index')
res.reset_index(level=0, inplace=True)
res
res.rename(columns={'Bat1':'1st Innings','Bat2':"2nd Innings"}, inplace=True)

In [83]:
# import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
# from matplotlib.figure import Figure


plt.figure(figsize=(20,20))
plt.figure().suptitle('test title', fontsize=20)
res.plot(kind='bar',x="Year",y=['1st Innings','2nd Innings'],color=['Blue','Green'], title=player_name)
# res.plot(kind='bar',x="Year",y='Bat2',color='Red',ax=ax, title=player_name)
plt.savefig("file.jpg",dpi=200)
plt.show

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  if __name__ == '__main__':

In [84]:

data_frame

,Bat1,Bat2,Runs,BF,SR,4s,6s,,Opposition,Ground,Start Date,Match No,Year
0,177,0,177,301,58.80,23,1,,v West Indies,Kolkata,6 Nov 2013,Test # 2101,2013
1,111,0,111,127,87.40,11,3,,v West Indies,Mumbai,14 Nov 2013,Test # 2102,2013
2,14,6,20,55,36.36,2,0,,v South Africa,Johannesburg,18 Dec 2013,Test # 2108,2013
3,0,25,25,47,53.19,2,1,,v South Africa,Durban,26 Dec 2013,Test # 2111,2013
4,72,19,91,179,50.83,10,1,,v New Zealand,Auckland,6 Feb 2014,Test # 2118,2014
5,0,31,31,100,31.00,4,0,,v New Zealand,Wellington,14 Feb 2014,Test # 2120,2014
6,28,6,34,89,38.20,3,0,,v England,Southampton,27 Jul 2014,Test # 2132,2014
7,43,6,49,107,45.79,6,0,,v Australia,Adelaide,9 Dec 2014,Test # 2148,2014
8,32,0,32,57,56.14,3,1,,v Australia,Brisbane,17 Dec 2014,Test # 2149,2014
9,53,39,92,223,41.25,7,4,,v Australia,Sydney,6 Jan 2015,Test # 2156,2015
10,6,0,6,9,66.66,1,0,,v Bangladesh,Fatullah,10 Jun 2015,Test # 2165,2015
11,9,4,13,40,32.50,2,0,,v Sri Lanka,Galle,12 Aug 2015,Test # 2176,2015
12,79,34,113,187,60.42,7,3,,v Sri Lanka,Colombo (PSS),20 Aug 2015,Test # 2177,2015
13,26,50,76,137,55.47,7,2,,v Sri Lanka,Colombo (SSC),28 Aug 2015,Test # 2179,2015
14,2,23,25,67,37.31,1,1,,v South Africa,Nagpur,25 Nov 2015,Test # 2189,2015
15,1,0,1,7,14.28,0,0,,v South Africa,Delhi,3 Dec 2015,Test # 2191,2015
16,9,41,50,82,60.97,3,3,,v West Indies,Gros Islet,9 Aug 2016,Test # 2215,2016
17,0,0,0,-,-,-,-,,v West Indies,Port of Spain,18 Aug 2016,Test # 2218,2016
18,35,68,103,160,64.37,11,1,,v New Zealand,Kanpur,22 Sep 2016,Test # 2221,2016
19,2,82,84,144,58.33,9,2,,v New Zealand,Kolkata,30 Sep 2016,Test # 2222,2016
20,51,0,51,63,80.95,3,2,,v New Zealand,Indore,8 Oct 2016,Test # 2223,2016
21,102,0,102,160,63.75,8,1,,v Sri Lanka,Nagpur,24 Nov 2017,Test # 2283,2017
22,65,50,115,151,76.15,12,2,,v Sri Lanka,Delhi,2 Dec 2017,Test # 2286,2017
23,11,10,21,89,23.59,1,0,,v South Africa,Cape Town,5 Jan 2018,Test # 2292,2018
24,10,47,57,101,56.43,8,1,,v South Africa,Centurion,13 Jan 2018,Test # 2293,2018
25,37,1,38,67,56.71,2,3,,v Australia,Adelaide,6 Dec 2018,Test # 2333,2018
26,63,5,68,132,51.51,5,0,,v Australia,Melbourne,26 Dec 2018,Test # 2337,2018
27,176,127,303,393,77.09,33,13,,v South Africa,Visakhapatnam,2 Oct 2019,Test # 2363,2019
28,14,0,14,35,40.00,1,0,,v South Africa,Pune,10 Oct 2019,Test # 2364,2019
29,212,0,212,255,83.13,28,6,,v South Africa,Ranchi,19 Oct 2019,Test # 2365,2019